services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=blog
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=blog
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U nameuser -d namedb" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data: